"""add_onboarding_and_risk_profile_to_users

Revision ID: ac0c4d6f07b6
Revises: a74ac0099f7c
Create Date: 2026-09-26 08:44:23.183372

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac0c4d6f07b6'
down_revision: str | Sequence[str] | None = 'a74ac0099f7c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_income', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('users', sa.Column('liquid_assets', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('users', sa.Column('investment_assets', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('users', sa.Column('total_liabilities', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('users', sa.Column('financial_goals', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('has_completed_financial_onboarding', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('risk_answers', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('portfolio_suggestion', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('has_completed_risk_onboarding', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_risk_onboarding')
    op.drop_column('users', 'portfolio_suggestion')
    op.drop_column('users', 'risk_answers')
    op.drop_column('users', 'risk_level')
    op.drop_column('users', 'risk_score')
    op.drop_column('users', 'has_completed_financial_onboarding')
    op.drop_column('users', 'financial_goals')
    op.drop_column('users', 'total_liabilities')
    op.drop_column('users', 'investment_assets')
    op.drop_column('users', 'liquid_assets')
    op.drop_column('users', 'monthly_income')
    # ### end Alembic commands ###
